[package]
name = "POC-Rust-Mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "3.0.1"
serde = "1.0.209"
tokio = "1.39.3"
